# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

jobConfigs:
  - name: ci-knative-serving-continuous
    org: knative
    repo: serving
    type: postsubmit
    issueRepo: serving
    slackChannels:
      - name: serving-api
        identity: CA4DNJ9A4
  - name: ci-knative-serving-istio-1.5-mesh
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: net-istio
        identity: C012AK2FPK7
  - name: ci-knative-serving-istio-1.5-no-mesh
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: net-istio
        identity: C012AK2FPK7
  - name: ci-knative-serving-istio-1.4-mesh
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: net-istio
        identity: C012AK2FPK7
  - name: ci-knative-serving-istio-1.4-no-mesh
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: net-istio
        identity: C012AK2FPK7
  - name: ci-knative-serving-gloo-0.17.1
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: net-gloo
        identity: C011X8RKZBR
  - name: ci-knative-serving-contour-latest
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: net-contour
        identity: C012J5TCS6Q
  - name: ci-knative-serving-kourier-stable
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: net-kourier
        identity: C012C0VQJAW
  - name: ci-knative-serving-ambassador-latest
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: net-ambassador
        identity: C011X8SPF8X
  - name: ci-knative-eventing-continuous
    org: knative
    repo: eventing
    type: postsubmit
    issueRepo: eventing
    slackChannels:
      - name: eventing
        identity: C9JP909F0
  - name: ci-knative-eventing-contrib-continuous
    org: knative
    repo: eventing-contrib
    type: postsubmit
    issueRepo: eventing-contrib
    slackChannels:
      - name: eventing-sources
        identity: CQBKVH4QY
      - name: eventing-channels
        identity: CR2141CGY
  - name: ci-knative-sandbox-eventing-kafka-broker-continuous
    org: knative-sandbox
    repo: eventing-kafka-broker
    type: postsubmit
    issueRepo: eventing-kafka-broker
  - name: ci-knative-test-infra-continuous
    org: knative
    repo: test-infra
    type: postsubmit
  - name: ci-google-knative-gcp-continuous
    org: google
    repo: knative-gcp
    type: postsubmit
