# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

jobConfigs:
  - name: continuous_serving_main_periodic
    org: knative
    repo: serving
    type: postsubmit
    issueRepo: serving
    slackChannels:
      - name: knative-serving-bots
        identity: C04MYJBP3H7
  - name: istio-latest-mesh_serving_main_periodic
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: knative-serving-bots
        identity: C04MYJBP3H7
  - name: istio-latest-no-mesh_serving_main_periodic
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: knative-serving-bots
        identity: C04MYJBP3H7
  - name: contour-latest_serving_main_periodic
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: knative-serving-bots
        identity: C04MYJBP3H7
  - name: s390x-contour-tests_serving_main_periodic
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: knative-serving-bots
        identity: C04MYJBP3H7
  - name: kourier-stable_serving_main_periodic
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: knative-serving-bots
        identity: C04MYJBP3H7
  - name: s390x-kourier-tests_serving_main_periodic
    org: knative
    repo: serving
    type: postsubmit
    slackChannels:
      - name: knative-serving-bots
        identity: C04MYJBP3H7
  - name: continuous_eventing_main_periodic
    org: knative
    repo: eventing
    type: postsubmit
    issueRepo: eventing
    slackChannels:
      - name: knative-eventing
        identity: C04LMU33V1S
  - name: s390x-e2e-tests_eventing_main_periodic
    org: knative
    repo: eventing
    type: postsubmit
    slackChannels:
      - name: knative-eventing
        identity: C04LMU33V1S
  - name: continuous_eventing-kafka-broker_main_periodic
    org: knative-extension
    repo: eventing-kafka-broker
    type: postsubmit
    issueRepo: eventing-kafka-broker
  - name: s390x-e2e-tests_operator_main_periodic
    org: knative
    repo: operator
    type: postsubmit
    slackChannels:
      - name: knative-operations
        identity: C050X5BGNNS
  - name: s390x-e2e-tests_client_main_periodic
    org: knative
    repo: client
    type: postsubmit
    slackChannels:
      - name: knative-client
        identity: C04LY4SKBQR
