presubmits:
  knative/serving:
  - repo-settings: null
    performance: true
  - build-tests: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - unit-tests: true
    dot-dev: true
    needs-monitor: true
  - integration-tests: true
    dot-dev: true
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-tests.sh
  - custom-test: upgrade-tests
    dot-dev: true
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-upgrade-tests.sh
  - custom-test: autotls-tests
    dot-dev: true
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-auto-tls-tests.sh
  - go-coverage: true
    go-coverage-threshold: 80
    dot-dev: true
  - custom-test: istio-1.5-mesh
    dot-dev: true
    always_run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version 1.5-latest --mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version 1.5-latest --mesh
  - custom-test: istio-1.5-no-mesh
    dot-dev: true
    always_run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version 1.5-latest --no-mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version 1.5-latest --no-mesh
  - custom-test: istio-1.4-mesh
    dot-dev: true
    always_run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version 1.4-latest --mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version 1.4-latest --mesh
  - custom-test: istio-1.4-no-mesh
    dot-dev: true
    always_run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version 1.4-latest --no-mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version 1.4-latest --no-mesh
  - custom-test: gloo-0.17.1
    dot-dev: true
    always_run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --gloo-version 0.17.1
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --gloo-version 0.17.1
  - custom-test: kourier-stable
    dot-dev: true
    always_run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --kourier-version stable
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --kourier-version stable
  - custom-test: contour-latest
    dot-dev: true
    always_run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --contour-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --contour-version latest
  - custom-test: ambassador-latest
    dot-dev: true
    always_run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --ambassador-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --ambassador-version latest
  - custom-test: https
    dot-dev: true
    always_run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --https
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --https
  knative/client:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  - custom-test: integration-tests-latest-release
    always_run: true
    command:
    - ./test/presubmit-integration-tests-latest-release.sh
    dot-dev: true
  knative/client-contrib:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  knative/eventing:
  - repo-settings: null
    performance: true
  - build-tests: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-tests.sh
  - custom-test: upgrade-tests
    dot-dev: true
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-upgrade-tests.sh
  - go-coverage: true
    dot-dev: true
  knative/eventing-contrib:
  - build-tests: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  knative/docs:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
    needs-dind: true
  - go-coverage: true
  - custom-test: markdown-link-check
    always_run: true
    optional: true
    command:
    - ./test/presubmit-link-check.sh
  knative/pkg:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  knative/test-infra:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  knative/caching:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  knative/sample-controller:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  knative/sample-source:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  google/knative-gcp:
  - repo-settings: null
    performance: true
  - build-tests: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - unit-tests: true
  - integration-tests: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-tests.sh
  - custom-test: wi-tests
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-wi-tests.sh
  - go-coverage: true
  knative/networking:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  knative/net-certmanager:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  knative/net-contour:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  knative/net-http01:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  knative/net-istio:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  - custom-test: latest
    dot-dev: true
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version latest
  knative/net-kourier:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  knative/website:
  - build-tests: false
  - unit-tests: false
  - integration-tests: false
  - go-coverage: false
  knative/community:
  - build-tests: false
  - unit-tests: false
  - integration-tests: false
  - go-coverage: false
  knative/operator:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
  - go-coverage: true
    dot-dev: true
  - custom-test: upgrade-tests
    dot-dev: true
    args:
    - --run-test
    - ./test/e2e-upgrade-tests.sh
  knative-sandbox/eventing-kafka:
  - build-tests: true
    dot-dev: true
    needs-dind: true
  - unit-tests: true
    dot-dev: true
    needs-dind: true
  - integration-tests: true
    dot-dev: true
    needs-dind: true
  - go-coverage: true
    dot-dev: true
    needs-dind: true
  knative-sandbox/eventing-rabbitmq:
  - build-tests: true
    dot-dev: true
  - unit-tests: true
    dot-dev: true
  - integration-tests: true
    dot-dev: true
periodics:
  knative/serving:
  - continuous: true
    timeout: 100
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.12"
    dot-dev: true
  - branch-ci: true
    release: "0.13"
    dot-dev: true
  - branch-ci: true
    release: "0.14"
    dot-dev: true
  - branch-ci: true
    release: "0.15"
    dot-dev: true
  - custom-job: istio-1.5-mesh
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version 1.5-latest --mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version 1.5-latest --mesh
    dot-dev: true
  - custom-job: istio-1.5-no-mesh
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version 1.5-latest --no-mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version 1.5-latest --no-mesh
    dot-dev: true
  - custom-job: istio-1.4-mesh
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version 1.4-latest --mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version 1.4-latest --mesh
    dot-dev: true
  - custom-job: istio-1.4-no-mesh
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version 1.4-latest --no-mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version 1.4-latest --no-mesh
    dot-dev: true
  - custom-job: gloo-0.17.1
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --gloo-version 0.17.1
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --gloo-version 0.17.1
    dot-dev: true
  - custom-job: kourier-stable
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --kourier-version stable
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --kourier-version stable
    dot-dev: true
  - custom-job: contour-latest
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --contour-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --contour-version latest
    dot-dev: true
  - custom-job: ambassador-latest
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --ambassador-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --ambassador-version latest
    dot-dev: true
  - custom-job: https
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --https
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --https
    dot-dev: true
  - nightly: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.12"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.13"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - auto-release: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - webhook-apicoverage: true
    dot-dev: true
  knative/client:
  - continuous: true
    dot-dev: true
  - branch-ci: true
    release: "0.12"
    dot-dev: true
  - branch-ci: true
    release: "0.13"
    dot-dev: true
  - branch-ci: true
    release: "0.14"
    dot-dev: true
  - branch-ci: true
    release: "0.15"
    dot-dev: true
  - nightly: true
    dot-dev: true
  - custom-job: tekton
    cron: 0 13 * * *
    command: ./test/tekton-tests.sh
    dot-dev: true
  - dot-release: true
    dot-dev: true
    release: "0.12"
  - dot-release: true
    dot-dev: true
    release: "0.13"
  - dot-release: true
    dot-dev: true
    release: "0.14"
  - dot-release: true
    dot-dev: true
    release: "0.15"
  - auto-release: true
    dot-dev: true
  knative/client-contrib:
  - continuous: true
    dot-dev: true
  knative/docs:
  - continuous: true
    needs-dind: true
  knative/eventing:
  - continuous: true
    timeout: 90
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.12"
    dot-dev: true
  - branch-ci: true
    release: "0.13"
    dot-dev: true
  - branch-ci: true
    release: "0.14"
    dot-dev: true
  - branch-ci: true
    release: "0.15"
    dot-dev: true
  - nightly: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.12"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.13"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - auto-release: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  knative/eventing-contrib:
  - continuous: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.12"
    dot-dev: true
  - branch-ci: true
    release: "0.13"
    dot-dev: true
  - branch-ci: true
    release: "0.14"
    dot-dev: true
  - branch-ci: true
    release: "0.15"
    dot-dev: true
  - nightly: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.12"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.13"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    dot-dev: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - auto-release: true
    dot-dev: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  knative/pkg:
  - continuous: true
    dot-dev: true
  knative/caching:
  - continuous: true
    dot-dev: true
  knative/sample-controller:
  - continuous: true
    dot-dev: true
  knative/sample-source:
  - continuous: true
    dot-dev: true
  knative/test-infra:
  - continuous: true
    dot-dev: true
  google/knative-gcp:
  - continuous: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.12"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.13"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - nightly: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.12"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
    env-vars:
    - ORG_NAME=google
  - dot-release: true
    release: "0.13"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
    env-vars:
    - ORG_NAME=google
  - dot-release: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
    env-vars:
    - ORG_NAME=google
  - dot-release: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
    env-vars:
    - ORG_NAME=google
  - auto-release: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
    env-vars:
    - ORG_NAME=google
  knative/net-certmanager:
  - continuous: true
    dot-dev: true
  - nightly: true
    dot-dev: true
  - dot-release: true
    dot-dev: true
  - auto-release: true
    dot-dev: true
  knative/net-contour:
  - continuous: true
    dot-dev: true
  - nightly: true
    dot-dev: true
  - dot-release: true
    dot-dev: true
  - auto-release: true
    dot-dev: true
  knative/net-http01:
  - continuous: true
    dot-dev: true
  - nightly: true
    dot-dev: true
  - dot-release: true
    dot-dev: true
  - auto-release: true
    dot-dev: true
  knative/net-istio:
  - continuous: true
    dot-dev: true
  - nightly: true
    dot-dev: true
  - dot-release: true
    dot-dev: true
    release: "0.14"
  - dot-release: true
    dot-dev: true
    release: "0.15"
  - auto-release: true
    dot-dev: true
  knative/net-kourier:
  - continuous: true
    dot-dev: true
  - nightly: true
    dot-dev: true
  - dot-release: true
    dot-dev: true
  - auto-release: true
    dot-dev: true
  knative/operator:
  - continuous: true
    dot-dev: true
  - branch-ci: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - nightly: true
    dot-dev: true
  - dot-release: true
    dot-dev: true
    env-vars:
    - ORG_NAME=knative-sandbox
  - auto-release: true
    dot-dev: true
    env-vars:
    - ORG_NAME=knative-sandbox
  knative-sandbox/eventing-kafka:
  - continuous: true
    dot-dev: true
    needs-dind: true
  - nightly: true
    dot-dev: true
    needs-dind: true
  - dot-release: true
    dot-dev: true
    needs-dind: true
    env-vars:
    - ORG_NAME=knative-sandbox
  - auto-release: true
    dot-dev: true
    needs-dind: true
    env-vars:
    - ORG_NAME=knative-sandbox
