presubmits:
  knative/serving:
  - repo-settings: null
    performance: true
  - build-tests: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - unit-tests: true
    needs-monitor: true
  - integration-tests: true
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-tests.sh
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: upgrade-tests
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-upgrade-tests.sh
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: autotls-tests
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-auto-tls-tests.sh
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - go-coverage: true
    go-coverage-threshold: 80
  - custom-test: istio-latest-mesh
    always-run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version latest --mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version latest --mesh
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: istio-latest-no-mesh
    always-run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version latest --no-mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version latest --no-mesh
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: istio-stable-mesh
    always-run: false
    optional: true
    run-if-changed: ^third_party/net-istio.yaml
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version stable --mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version stable --mesh
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: istio-stable-no-mesh
    always-run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version stable --no-mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version stable --no-mesh
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: gloo-0.17.1
    always-run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --gloo-version 0.17.1
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --gloo-version 0.17.1
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: kourier-stable
    always-run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --kourier-version stable
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --kourier-version stable
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: contour-latest
    always-run: false
    run-if-changed: ^third_party/contour-latest/*
    args:
    - --run-test
    - ./test/e2e-tests.sh --contour-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --contour-version latest
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: ambassador-latest
    always-run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --ambassador-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --ambassador-version latest
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: kong-latest
    always-run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --kong-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --kong-version latest
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - custom-test: https
    always-run: false
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --https
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --https
  knative/client:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  - custom-test: integration-tests-latest-release
    always-run: true
    command:
    - ./test/presubmit-integration-tests-latest-release.sh
  knative/client-contrib:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  knative/eventing:
  - repo-settings: null
    performance: true
  - build-tests: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - unit-tests: true
  - integration-tests: true
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-tests.sh
  - custom-test: conformance-tests
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-conformance-tests.sh
  - custom-test: upgrade-tests
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-upgrade-tests.sh
  - go-coverage: true
  knative/eventing-contrib:
  - build-tests: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  knative/docs:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
    needs-dind: true
  - go-coverage: true
  - custom-test: markdown-link-check
    always-run: true
    optional: true
    command:
    - ./test/presubmit-link-check.sh
  knative/pkg:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  knative/test-infra:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  knative/caching:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  knative-sandbox/sample-controller:
  - build-tests: true
  - unit-tests: true
  knative-sandbox/sample-source:
  - build-tests: true
  - unit-tests: true
  google/knative-gcp:
  - repo-settings: null
    performance: true
  - build-tests: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - unit-tests: true
  - integration-tests: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-tests.sh
  - custom-test: wi-tests
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
    needs-monitor: true
    args:
    - --run-test
    - ./test/e2e-wi-tests.sh
  - go-coverage: true
  knative/networking:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  knative-sandbox/net-certmanager:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  knative-sandbox/net-contour:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  knative-sandbox/net-http01:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  knative-sandbox/net-istio:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  - custom-test: latest
    optional: true
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version latest
  knative-sandbox/net-kourier:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  knative/website:
  - build-tests: false
  - unit-tests: false
  - integration-tests: false
  - go-coverage: false
  knative/community:
  - build-tests: false
  - unit-tests: false
  - integration-tests: false
  - go-coverage: false
  knative/operator:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  - go-coverage: true
  - custom-test: upgrade-tests
    args:
    - --run-test
    - ./test/e2e-upgrade-tests.sh
  knative-sandbox/discovery:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
  knative-sandbox/eventing-kafka:
  - build-tests: true
    needs-dind: true
  - unit-tests: true
    needs-dind: true
  - integration-tests: true
    needs-dind: true
  - go-coverage: true
    needs-dind: true
  knative-sandbox/eventing-kafka-broker:
  - build-tests: true
    needs-dind: true
  - unit-tests: true
    needs-dind: true
  - integration-tests: true
    needs-dind: true
  - go-coverage: true
    needs-dind: true
  knative-sandbox/eventing-rabbitmq:
  - build-tests: true
  - unit-tests: true
  - integration-tests: true
periodics:
  knative/serving:
  - continuous: true
    timeout: 100
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.14"
  - branch-ci: true
    release: "0.15"
  - branch-ci: true
    release: "0.16"
  - branch-ci: true
    release: "0.17"
  - custom-job: istio-latest-mesh
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version latest --mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version latest --mesh
  - custom-job: istio-latest-no-mesh
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version latest --no-mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version latest --no-mesh
  - custom-job: istio-stable-mesh
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version stable --mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version stable --mesh
  - custom-job: istio-stable-no-mesh
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version stable --no-mesh
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --istio-version stable --no-mesh
  - custom-job: gloo-0.17.1
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --gloo-version 0.17.1
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --gloo-version 0.17.1
  - custom-job: kourier-stable
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --kourier-version stable
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --kourier-version stable
  - custom-job: contour-latest
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --contour-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --contour-version latest
  - custom-job: ambassador-latest
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --ambassador-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --ambassador-version latest
  - custom-job: kong-latest
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --kong-version latest
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --kong-version latest
  - custom-job: https
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --https
    - --run-test
    - ./test/e2e-auto-tls-tests.sh --https
  - nightly: true
    reporter_config:
      slack:
        channel: serving-api
        job_states_to_report:
        - failure
        report_template: '"The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"'
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.16"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.17"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - auto-release: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - webhook-apicoverage: true
  knative/client:
  - continuous: true
  - branch-ci: true
    release: "0.13"
  - branch-ci: true
    release: "0.14"
  - branch-ci: true
    release: "0.15"
  - branch-ci: true
    release: "0.16"
  - nightly: true
  - custom-job: tekton
    cron: 0 13 * * *
    command: ./test/tekton-tests.sh
  - dot-release: true
    release: "0.13"
  - dot-release: true
    release: "0.14"
  - dot-release: true
    release: "0.15"
  - dot-release: true
    release: "0.16"
  - auto-release: true
  knative/client-contrib:
  - continuous: true
  knative/docs:
  - continuous: true
    needs-dind: true
  knative/eventing:
  - continuous: true
    timeout: 90
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.14"
  - branch-ci: true
    release: "0.15"
  - branch-ci: true
    release: "0.16"
  - branch-ci: true
    release: "0.17"
  - nightly: true
    reporter_config:
      slack:
        channel: eventing
        job_states_to_report:
        - failure
        report_template: '"The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"'
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.16"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.17"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - auto-release: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  knative/eventing-contrib:
  - continuous: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.13"
  - branch-ci: true
    release: "0.14"
  - branch-ci: true
    release: "0.15"
  - branch-ci: true
    release: "0.16"
  - nightly: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.13"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.16"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - auto-release: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  knative/pkg:
  - continuous: true
  knative/caching:
  - continuous: true
  knative-sandbox/sample-controller:
  - continuous: true
  knative-sandbox/sample-source:
  - continuous: true
  knative/test-infra:
  - continuous: true
  google/knative-gcp:
  - continuous: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.13"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.16"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - nightly: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.13"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.14"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - dot-release: true
    release: "0.16"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - auto-release: true
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  knative-sandbox/net-certmanager:
  - continuous: true
  - nightly: true
    reporter_config:
      slack:
        channel: net-certmanager
        job_states_to_report:
        - failure
        report_template: '"The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"'
  - dot-release: true
  - auto-release: true
  knative-sandbox/net-contour:
  - continuous: true
  - nightly: true
    reporter_config:
      slack:
        channel: net-contour
        job_states_to_report:
        - failure
        report_template: '"The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"'
  - dot-release: true
  - auto-release: true
  knative-sandbox/net-http01:
  - continuous: true
  - nightly: true
    reporter_config:
      slack:
        channel: net-http01
        job_states_to_report:
        - failure
        report_template: '"The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"'
  - dot-release: true
  - auto-release: true
  knative-sandbox/net-istio:
  - continuous: true
  - nightly: true
    reporter_config:
      slack:
        channel: net-istio
        job_states_to_report:
        - failure
        report_template: '"The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"'
  - custom-job: latest
    command:
    - ./test/presubmit-tests.sh
    args:
    - --run-test
    - ./test/e2e-tests.sh --istio-version latest
  - dot-release: true
    release: "0.14"
  - dot-release: true
    release: "0.15"
  - dot-release: true
    release: "0.16"
  - auto-release: true
  knative-sandbox/net-kourier:
  - continuous: true
  - nightly: true
    reporter_config:
      slack:
        channel: net-kourier
        job_states_to_report:
        - failure
        report_template: '"The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"'
  - dot-release: true
  - auto-release: true
  knative/operator:
  - continuous: true
  - branch-ci: true
    release: "0.15"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - branch-ci: true
    release: "0.16"
    resources:
      requests:
        memory: 12Gi
      limits:
        memory: 16Gi
  - nightly: true
  - dot-release: true
  - auto-release: true
  knative-sandbox/discovery:
  - continuous: true
  - nightly: true
  - dot-release: true
  - auto-release: true
  knative-sandbox/eventing-kafka:
  - continuous: true
    needs-dind: true
  - nightly: true
    needs-dind: true
  - dot-release: true
    needs-dind: true
  - auto-release: true
    needs-dind: true
  knative-sandbox/eventing-kafka-broker:
  - continuous: true
    needs-dind: true
  - nightly: true
    needs-dind: true
  - dot-release: true
    needs-dind: true
  - auto-release: true
    needs-dind: true
